CALLING nextFunction
HERE 5
got error from nextObject: MongoError: operation was interrupted
restarting cursor soon
calling nextObject
CALLING nextFunction
!init
couldn't save for later, discon hasHandler false true






got error from nextObject: MongoError: connection 2 to c615.lighthouse.4.mongolayer.com:10615 closed
restarting cursor soon
calling nextObject
CALLING nextFunction
!init
RSISCONN: hasPrimary
RSISCONN: hasPrimary
couldn't save for later, discon hasHandler false true
trying to get server


it breaks if we manage to retry BEFORE the tcp close
or if somehow the pool still hasSockets?
